[tool.poetry]
name = "BPMN_evaluation_framework"
version = "0.1.0"
description = ""
authors = ["raheleh <raheleh.hadian@sap.com>"]
readme = "README.md"
packages = [
    #{ include = "bpmn_evaluation_framework" },
    { include = "model_evaluation" },
]

[[tool.poetry.source]]
name = "PyPI"
priority = "primary"


[tool.poetry.dependencies]
python = ">=3.11,<3.13"
#generative-ai-hub-sdk = {extras = ["all"], version = "^4.10.2"}
ipykernel = "^6.29.5"
scikit-learn = "^1.6.1"
sentence-transformers = "^4.1.0"
pandas = "^2.2.3"
ipywidgets = "^8.1.8"
matplotlib = "^3.10.7"
lxml = "^6.0.2"
pydantic = "^2.13.4"
marimo = "^0.13"
plotly = "^5.24.0"
nbformat = "^5.10.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["model_evaluation"]


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"